#!/usr/bin/env python3
"""Head-to-head evaluation of Model A (LightGBM) and Model B (embeddings).

The headline F1 on this task is not the interesting number. Malicious packages
and popular packages are so different in shape that almost any classifier
separates them, and reporting that split alone produces an impressive figure
that says nothing about whether the model works on a real upload.

So this script reports three slices:

  overall   -- every held-out package. The flattering number.
  popular   -- malicious vs. top-download packages. Flattering for the same reason.
  obscure   -- malicious vs. HARD NEGATIVES: small, amateur, obscure but benign
               packages sampled at random from PyPI. **This is the honest number.**
               It answers the question that actually matters: when a first-time
               author uploads a rough 40-line package, does the model flag it?

The gap between `overall` and `obscure` is the most informative result this
project produces, and it belongs in the README.

Usage:
    python ml/evaluate.py
"""

from __future__ import annotations

import argparse
import json
import pickle
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from sklearn.metrics import (  # noqa: E402
    average_precision_score,
    confusion_matrix,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)

from config import FEATURES_PARQUET, MODELS, REPORTS, ensure_dirs  # noqa: E402
from features import feature_names  # noqa: E402
from split import dataset_splits, xy  # noqa: E402

SIZE_FEATURES = {"pkg_n_files", "pkg_loc", "pkg_n_py_files", "pkg_loc_per_file"}


def slice_metrics(y: np.ndarray, prob: np.ndarray, thr: float) -> dict:
    """Metrics for one slice. AUCs need both classes present."""
    pred = (prob >= thr).astype(int)
    both = len(np.unique(y)) == 2
    tn, fp, fn, tp = confusion_matrix(y, pred, labels=[0, 1]).ravel()
    prec = precision_score(y, pred, zero_division=0)
    rec = recall_score(y, pred, zero_division=0)
    return {
        "n": int(len(y)),
        "n_positive": int(y.sum()),
        "roc_auc": float(roc_auc_score(y, prob)) if both else None,
        "pr_auc": float(average_precision_score(y, prob)) if both else None,
        "precision": float(prec),
        "recall": float(rec),
        "f1": float(2 * prec * rec / (prec + rec)) if prec + rec else 0.0,
        "tp": int(tp), "fp": int(fp), "tn": int(tn), "fn": int(fn),
        "false_positive_rate": float(fp / max(fp + tn, 1)),
    }


def evaluate_model(name: str, y: np.ndarray, prob: np.ndarray,
                   pool: np.ndarray, thr: float, latency_ms: float) -> dict:
    res = {"model": name, "threshold": thr, "latency_ms_per_package": latency_ms,
           "slices": {}}
    res["slices"]["overall"] = slice_metrics(y, prob, thr)

    for slice_name, mask in (
        ("popular", (pool == "popular") | (pool == "malicious")),
        ("obscure", (pool == "obscure") | (pool == "malicious")),
    ):
        if mask.sum():
            res["slices"][slice_name] = slice_metrics(y[mask], prob[mask], thr)
    return res


def plot_curves(results: dict[str, tuple[np.ndarray, np.ndarray]], out: Path) -> None:
    """ROC and PR curves for every model on one pair of axes."""
    fig, (ax_roc, ax_pr) = plt.subplots(1, 2, figsize=(11, 4.5))

    for name, (y, prob) in results.items():
        if len(np.unique(y)) < 2:
            continue
        fpr, tpr, _ = roc_curve(y, prob)
        ax_roc.plot(fpr, tpr, label=f"{name} (AUC {roc_auc_score(y, prob):.3f})")
        prec, rec, _ = precision_recall_curve(y, prob)
        ax_pr.plot(rec, prec, label=f"{name} (AP {average_precision_score(y, prob):.3f})")

    ax_roc.plot([0, 1], [0, 1], "k--", lw=0.8, alpha=0.5)
    ax_roc.set(xlabel="False positive rate", ylabel="True positive rate", title="ROC")
    ax_pr.set(xlabel="Recall", ylabel="Precision", title="Precision-Recall")
    for ax in (ax_roc, ax_pr):
        ax.legend(fontsize=8)
        ax.grid(alpha=0.3)

    fig.tight_layout()
    fig.savefig(out, dpi=140)
    plt.close(fig)


def write_report(evals: list[dict], importance: list[dict] | None, out: Path) -> None:
    lines = ["# Model comparison", "",
             "Generated by `ml/evaluate.py`. All numbers are on the same grouped",
             "held-out split (no package name appears in both train and test).", ""]

    lines += ["## The number that matters", "",
              "`obscure` scores malicious packages against **hard negatives** -- small,",
              "amateur, obscure but legitimate packages sampled at random from PyPI.",
              "`popular` scores them against top-download projects, which are so",
              "different in shape that the result flatters any classifier.", "",
              "A large gap between the two means the model is leaning on package size",
              "rather than behaviour.", ""]

    for slice_name in ("overall", "popular", "obscure"):
        lines += [f"## Slice: `{slice_name}`", "",
                  "| model | n | ROC-AUC | PR-AUC | precision | recall | F1 | FPR |",
                  "|---|---|---|---|---|---|---|---|"]
        for ev in evals:
            s = ev["slices"].get(slice_name)
            if not s:
                continue
            fmt = lambda v: f"{v:.4f}" if isinstance(v, float) else "n/a"
            lines.append(
                f"| {ev['model']} | {s['n']} | {fmt(s['roc_auc'])} | {fmt(s['pr_auc'])} "
                f"| {fmt(s['precision'])} | {fmt(s['recall'])} | {fmt(s['f1'])} "
                f"| {fmt(s['false_positive_rate'])} |"
            )
        lines.append("")

    lines += ["## Inference cost", "",
              "| model | ms per package |", "|---|---|"]
    for ev in evals:
        lines.append(f"| {ev['model']} | {ev['latency_ms_per_package']:.2f} |")
    lines.append("")

    if importance:
        lines += ["## Top features (LightGBM gain)", "",
                  "| # | feature | gain |", "|---|---|---|"]
        for i, row in enumerate(importance[:20], 1):
            lines.append(f"| {i} | `{row['feature']}` | {row['gain']:.0f} |")
        lines.append("")

        top2 = {r["feature"] for r in importance[:2]}
        if top2 & SIZE_FEATURES:
            lines += ["> **Leakage warning.** A raw size feature ranks in the top 2 by",
                      "> gain, which suggests the model is partly learning 'small package",
                      "> == malicious'. Grow the hard-negative pool in `acquire_benign.py`",
                      "> before trusting these numbers.", ""]
        else:
            lines += ["> No raw size feature ranks in the top 2 by gain, so the model is",
                      "> keying on behaviour rather than package size.", ""]

    out.write_text("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", type=Path, default=FEATURES_PARQUET)
    args = ap.parse_args()

    ensure_dirs()
    df = pd.read_parquet(args.data)
    if df["label"].nunique() < 2:
        print("[error] the dataset contains only one class -- nothing to evaluate")
        return 1

    cols = feature_names()
    test_df = dataset_splits(df).test
    X_te, y_te = xy(test_df, cols)
    pool = test_df["pool"].to_numpy()

    evals: list[dict] = []
    curves: dict[str, tuple[np.ndarray, np.ndarray]] = {}

    # --- Model A ------------------------------------------------------------
    gbdt_path = MODELS / "gbdt.pkl"
    if gbdt_path.exists():
        with open(gbdt_path, "rb") as fh:
            art = pickle.load(fh)
        t0 = time.perf_counter()
        prob = art["model"].predict(X_te)
        latency = (time.perf_counter() - t0) / max(len(X_te), 1) * 1000
        evals.append(evaluate_model("LightGBM (features)", y_te, prob, pool,
                                    art["threshold"], latency))
        curves["LightGBM (features)"] = (y_te, prob)
        gbdt_prob, gbdt_thr = prob, art["threshold"]
    else:
        print(f"[warn] {gbdt_path} not found -- run train_gbdt.py")

    # --- Model B ------------------------------------------------------------
    embed_path = MODELS / "embed.pkl"
    cache_path = Path(__file__).resolve().parents[1] / "data" / "cache" / "embeddings.npz"
    if embed_path.exists() and cache_path.exists():
        with open(embed_path, "rb") as fh:
            art = pickle.load(fh)
        with np.load(cache_path) as z:
            cache = {k: z[k] for k in z.files}
        # Model B has only embedded the packages it was trained with. Scoring
        # the rest as zero vectors would be unfair to it, so the head-to-head
        # runs on the packages both models can see.
        has = np.array([f"{p}@{v}" in cache
                        for p, v in zip(test_df["package"], test_df["version"])])
        print(f"[B] {int(has.sum())} of {len(has)} test packages have embeddings")
        E = np.vstack([cache[f"{p}@{v}"] for p, v in
                       zip(test_df["package"][has], test_df["version"][has])])
        t0 = time.perf_counter()
        prob = art["head"].predict_proba(art["scaler"].transform(E))[:, 1]
        latency = (time.perf_counter() - t0) / max(len(E), 1) * 1000
        evals.append(evaluate_model("Embeddings + LR (embedded subset)", y_te[has], prob,
                                    pool[has], art["threshold"], latency))
        curves["Embeddings + LR (embedded subset)"] = (y_te[has], prob)
        if "gbdt_prob" in locals():
            evals.append(evaluate_model("LightGBM (embedded subset)", y_te[has],
                                        gbdt_prob[has], pool[has], gbdt_thr, 0.0))
    else:
        print(f"[warn] {embed_path} not found -- run train_embed.py")

    if not evals:
        print("[error] no trained models found")
        return 1

    importance = None
    imp_path = REPORTS / "gbdt_importance.json"
    if imp_path.exists():
        importance = json.loads(imp_path.read_text())

    plot_curves(curves, REPORTS / "curves.png")
    write_report(evals, importance, REPORTS / "comparison.md")
    (REPORTS / "metrics.json").write_text(json.dumps(evals, indent=2))

    # --- console summary ----------------------------------------------------
    print("\n" + "=" * 68)
    for ev in evals:
        print(f"\n{ev['model']}  (threshold {ev['threshold']:.3f})")
        for slice_name in ("overall", "popular", "obscure"):
            s = ev["slices"].get(slice_name)
            if not s:
                continue
            tag = "  <-- the honest number" if slice_name == "obscure" else ""
            pr = f"{s['pr_auc']:.4f}" if s["pr_auc"] is not None else "n/a"
            print(f"  {slice_name:<8} n={s['n']:<5} PR-AUC {pr}  "
                  f"P {s['precision']:.3f}  R {s['recall']:.3f}  "
                  f"F1 {s['f1']:.3f}  FPR {s['false_positive_rate']:.3f}{tag}")
    print("\n" + "=" * 68)
    print(f"report -> {REPORTS / 'comparison.md'}")
    print(f"curves -> {REPORTS / 'curves.png'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
